# Generated by Django 5.2.15 on 2026-09-06 07:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
import submissions.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='كود تتبع الطلب')),
                ('author_name', models.CharField(max_length=200, verbose_name='اسم الباحث / مقدم المشاركة كاملاً')),
                ('academic_degree', models.CharField(choices=[('professor', 'أستاذ بروفيسور (Professor)'), ('assoc_prof', 'أستاذ مشارك (Associate Professor)'), ('asst_prof', 'أستاذ مساعد (Assistant Professor)'), ('lecturer', 'محاضر (Lecturer)'), ('researcher', 'باحث أكاديمي (Researcher)'), ('postgrad', 'طالب دراسات عليا (Postgraduate Student)'), ('undergrad', 'طالب جامعي / مشروع متميز (Undergraduate)')], default='researcher', max_length=30, verbose_name='الدرجة العلمية / الرتبة')),
                ('university', models.CharField(max_length=200, verbose_name='الجامعة / المؤسسة الأكاديمية')),
                ('faculty_and_dept', models.CharField(max_length=200, verbose_name='الكلية والقسم التخصصي')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني للباحث')),
                ('phone', models.CharField(max_length=30, verbose_name='رقم الهاتف / الواتساب')),
                ('conference_title', models.CharField(default='المؤتمر العلمي الدولي الشامل - جامعة البطانة', max_length=255, verbose_name='اسم المؤتمر / الفعالية')),
                ('academic_domain', models.CharField(choices=[('medical', '🩺 العلوم الطبية والصحية والتمريض'), ('education', '📚 العلوم التربوية والمناهج وتطوير التعليم'), ('cs_it', '💻 الحاسوب والذكاء الاصطناعي وتقانة المعلومات'), ('engineering', '⚙️ العلوم الهندسية والتطبيقية'), ('economics', '📈 العلوم الاقتصادية والإدارية والمحاسبة'), ('agriculture', '🌾 العلوم الزراعية والبيطرية والإنتاج الحيواني'), ('humanities', '⚖️ العلوم الإنسانية والقانونية والدراسات الإسلامية واللغات'), ('other', '🌐 مجال وتخصص أكاديمي آخر')], default='cs_it', max_length=30, verbose_name='المجال والقطاع الأكاديمي')),
                ('research_track', models.CharField(max_length=255, verbose_name='المحور العلمي التخصصي للبحث')),
                ('participation_type', models.CharField(choices=[('full_paper', 'ورقة علمية / بحث كامل (Full Research Paper)'), ('abstract', 'ملخص بحثي موسع (Extended Abstract)'), ('poster', 'بوستر / ملصق علمي (Scientific Poster)'), ('innovative_project', 'مشروع ابتكاري / براءة اختراع (Innovative Project)'), ('workshop', 'مقترح ورشة عمل تفاعلية (Workshop Proposal)')], default='full_paper', max_length=30, verbose_name='نوع المشاركة')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان البحث أو المشروع العلمي')),
                ('abstract', models.TextField(blank=True, null=True, verbose_name='ملخص البحث (Abstract)')),
                ('file', models.FileField(upload_to='submissions_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), submissions.models.validate_file_size], verbose_name='ملف البحث (Word أو PDF)')),
                ('status', models.CharField(choices=[('submitted', 'تم الاستلام بنجاح (بانتظار الفحص الإداري الأولي)'), ('defective_file', '⚠️ تنبيه: الملف غير صالح / تالف (مطلوب إعادة الرفع)'), ('under_scientific_review', '🔬 محال للشؤون العلمية (قيد التحكيم والتقييم الأكاديمي)'), ('revision_required', '📝 قيد المراجعة: مطلوب إجراء تعديلات أكاديمية على البحث'), ('accepted', '🎉 مبارك! تم قبول البحث للمشاركة في المؤتمر'), ('rejected', '❌ نعتذر عن عدم قبول البحث في الدورة الحالية')], default='submitted', max_length=35, verbose_name='حالة الطلب')),
                ('manager_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات مدير المنصة')),
                ('manager_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ فحص المدير')),
                ('scientific_score', models.PositiveIntegerField(blank=True, null=True, verbose_name='درجة التحكيم العلمي (من 100)')),
                ('scientific_decision_notes', models.TextField(blank=True, null=True, verbose_name='تقرير وتوصيات الشؤون العلمية ولجنة التحكيم')),
                ('scientific_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ مراجعة الشؤون العلمية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('manager_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='تم الفحص بواسطة المدير')),
                ('scientific_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL, verbose_name='المحكم المسؤول')),
            ],
            options={
                'verbose_name': 'مشاركة / ورقة علمية مقدمة',
                'verbose_name_plural': 'المشاركات والأوراق العلمية للمؤتمرات',
                'ordering': ['-created_at'],
            },
        ),
    ]
